// <auto-generated />
using PDFFormFiller.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace PDFFormFiller.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PDFFormFiller.Models.FieldNaming", b =>
                {
                    b.Property<string>("ModelFieldName")
                        .HasColumnType("text");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<string>("PdfFieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ModelFieldName");

                    b.ToTable("FieldNaming");

                    b.HasData(
                        new
                        {
                            ModelFieldName = "EnlistedOccupationYes",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].Yes_business[0]"
                        },
                        new
                        {
                            ModelFieldName = "EnlistedOccupationNo",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].No_business[0]"
                        },
                        new
                        {
                            ModelFieldName = "InnovativeEmployerYes",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].Yes_inn[0]"
                        },
                        new
                        {
                            ModelFieldName = "InnovativeEmployerNo",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].No_inn[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralOrganizationName",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_des_part[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalFirstName",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_first_name[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalMiddleName",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_mid_name[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalLastName",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_last_name[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalPhoneNumber",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_phone_number[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalAlternatePhoneNumber",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_alternate_phone[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalFaxNumber",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_fax_number[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalEmail",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_Email[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalOralLanguage",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].rb_language_oral[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralPrincipalWrittenLanguage",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].rb_language_written[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternateFirstName",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_first_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternateMiddleName",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_mid_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternateLastName",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_last_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternatePhoneNumber",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_phone_number2[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternateAlternatePhoneNumber",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_alternate_phone2[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternateFaxNumber",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_fax_number2[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternateEmail",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].txtF_Email2[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternateOralLanguage",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].rb_language_oral2[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReferralAlternateWrittenLanguage",
                            Page = 1,
                            PdfFieldName = "EMP5624_E[0].Page1[0].rb_language_written2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerRevenueDeductionsAccountNumber1",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].num_Company_Code[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerRevenueDeductionsAccountNumber2",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].num_Company_Code[1]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerBusinessLegalName",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Emp_Legal[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerBusinessAddress1",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Mail_Adress1[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerBusinessAddress2",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Mail_Adress2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerBusinessCity",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_City[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerBusinessProvince",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Province[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerBusinessCountry",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Country[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerBusinessPostalCode",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Postal_Code[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerMailingAddress1",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Mail_Adress2-1[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerMailingAddress2",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Mail_Adress2-2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerMailingCity",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_City2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerMailingProvince",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Province2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerMailingCountry",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Country2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerMailingPostalCode",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Postal_Code2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerWebsite",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Employer_Web_Address[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerBusinessStartDate",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Employer_Date_Business[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerIsSoleProprietorship",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].cb_sole_propietor[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerIsPartnership",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].cb_partnership[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerIsCorporation",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].cb_individual[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerIsCoOperative",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].cb_society[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerIsNonProfit",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].cb_not_profit[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerIsRegisteredCharity",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].cb_registred[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerNumberOfEmployees",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_amout_employees[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAnnualGrossRevenue",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_business_revenu[0]"
                        },
                        new
                        {
                            ModelFieldName = "ReceiveSupportThroughProgram",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].rb_receive_prog[0]"
                        },
                        new
                        {
                            ModelFieldName = "SupportDetails",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_If_Yes2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalJobTitle",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_position_title[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalFirstName",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_first_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalMiddleName",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_mid_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalLastName",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_last_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalPhoneNumber",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_phone_number2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalAlternatePhoneNumber",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_alternate_phone2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalFaxNumber",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_fax_number2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalEmail",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_Email2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalOralLanguage",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].rb_language_oral2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerPrincipalWrittenLanguage",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].rb_language_written2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateJobTitle",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_other_position_title[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateFirstName",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_other_first_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateMiddleName",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_other_mid_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateLastName",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_other_last_name2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternatePhoneNumber",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_other_phone_number2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateAlternatePhoneNumber",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_other_alternate_phone2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateFaxNumber",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_other_fax_number2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateEmail",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].txtF_other_Email2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateOralLanguage",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].rb_other_language_oral2[0]"
                        },
                        new
                        {
                            ModelFieldName = "EmployerAlternateWrittenLanguage",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].rb_other_anguage_written2[0]"
                        },
                        new
                        {
                            ModelFieldName = "AppointingThirdParty",
                            Page = 2,
                            PdfFieldName = "EMP5624_E[0].Page2[0].rb_tiers[0]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
